### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Spazzy757
# description: This will be meta HTML tag content. This can be ignored.
description: Personal Website of Brendan Kamp
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Brendan Kamp
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Software Engineer
# email: Your E-Mail address for the email button.
email: brendankamp757@gmail.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: Spazzy757
codepen_username: 
dev_username: 
linkedin_username: brendan-kamp-757e
twitter_username: Spazzy757

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: My main passion is for everything Code, from web development to deep learning and all that is in-between. I started my career as a frontend developer, designing small web applications. I got really bored, very fast so I started looking at what I could do to challenge myself and along came Python. I've been working mainly in infrastructure and cloud but still keep my finger on the pulse of software.

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
# cv_download_link: https://example.com/

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: Currently I am a consultant at <a href="https://container-solutions.com">Container Solutions</a>, so if you wish to obtain any of my services feel free to email me directly or get in touch on our  <a href="https://container-solutions.com">website</a>.

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: spazzy757/spazzy757.com
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    - patchapallet
    - redis-sentinel
    - TaskViewer
    - falcon-blog-tutorial
    - grpc-blog-tutorial
    - hug-blog-tutorial
    - kong-blog-tutorial
    - kong-oauth
    - kong-docker-compose-cassandra
    - kong-kubernetes
    - tracker
    - AsyncHelper
    - ecommerce-test
    - go-proxy-pass
    - service-blox-oauth
    - geyser-sensor
    - newGitTest

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
